version: '3'
services:
  redis:
    image: redis:7.0.8
    command: 
    - "redis-server"
    - "--appendonly"
    - "yes"
    - "--save"
    - "''"
    volumes:
      - redis-storage:/data

  jals:
    build: ./jals
    environment:
      - EMOJI=true
      - REDIS_ADDRESS=redis:6379
      - REDIS_DB=0
    ports:
      - "8080:8080"


volumes:
  redis-storage: {}
